spring.application.name=insurance-core

# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/insurance_brokerage
spring.datasource.username=postgres
spring.datasource.password=Chimichanga123adentro
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (JPA)
# 'update' actualiza el esquema automáticamente, útil en desarrollo. 
# Si tu script SQL ya creó todo perfecto, puedes usar 'validate' o 'none'.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect